name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Se você precisar processar arquivos antes da publicação
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # ou ./dist, ./docs, etc. dependendo da sua estrutura
