name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create package.json
        run: |
          echo '{
            "name": "meu-projeto",
            "version": "1.0.0",
            "dependencies": {
              "dependencia1": "^1.0.0",
              "dependencia2": "^2.0.0"
            }
          }' > package.json
          
      - name: Install dependencies
        run: npm install